# Party system to use: 'parties' or 'mmocore'
# parties - Uses the Parties plugin
# mmocore - Uses MMOCore party system
party-system: "parties"

# Distance in blocks in which players can roll for items
roll-distance: 100.0

# Time in seconds players have to roll for items
roll-time: 30

# Messages
messages:
  reload-success: "Configuration successfully reloaded!"
  loot-dropped: "<newline> <green>Item dropped</green> <gray>[</gray><item><gray>]</gray><newline> <gray><hover:show_text:'<gray>Click to make priority roll.'><click:run_command:/roll <item_name>><white>Need</click></hover> | <hover:show_text:'<gray>Click to make a non-priority roll.'><click:run_command:/greed <item_name>><yellow>Greed</click></hover> | <hover:show_text:'<gray>Click to pass the item.'><click:run_command:/pass <item_name>><red>Pass</click></hover><newline>"
  countdown: "<gray>Roll for item [</gray><item><gray>]</gray> will end in <time> seconds!"
  player-rolled: "<yellow>Player <player> rolls <gold><roll></gold> for</yellow> <gray>[</gray><item><gray>]</gray>"
  player-greed-rolled: "<yellow>Player <player> greed rolls <gray><roll></gray> for</yellow> <gray>[</gray><item><gray>]</gray>"
  player-skipped-roll: "<yellow>Player <player> passes on</yellow> <gray>[</gray><item><gray>]</gray>"
  roll-winner: "<green>Player <player> won</green> <gray>[</gray><item><gray>]</gray> <green>with roll <gold><roll></gold>"
  greed-roll-winner: "<green>Player <player> won</green> <gray>[</gray><item><gray>]</gray> <green>with greed roll <gray><roll></gray>"
  available-items: "<gray>Active rolls:"
  available-item-format: " <dark_gray>- <click:run_command:/roll <item_name>><gray>[</gray><item><gray>]</gray></click>"
  available-items-to-skip: "<gray>Active rolls:"
  available-skip-item-format: " <dark_gray>- <click:run_command:/pass <item_name>><gray>[</gray><item><gray>]</gray></click>"
  no-active-roll: "<red>No active rolls!"
  no-active-greed-roll: "<red>No active rolls!"
  no-sessions-to-skip: "<red>No active rolls!"
  not-in-party: "<red>You must be in a party to use the roll command!"
  no-rolls-unlocked: "<gray>Nobody rolled for <gray>[</gray><item><gray>]</gray>!"
  item-not-found: "<red>Item '<item>' not found!"
